image:
  file: .gitpod.Dockerfile2

tasks:
  - init: npm install

vscode:
  extensions:
    - mhutchie.git-graph@1.27.0:LVHVLytklbNt56Sgknun+Q==
    - eamodio.gitlens@10.2.1:WIWu3zHU4VPT8r/v866LUw==

ports:
  - port: 8000
